"use client"
import { GlobalStyle } from "../../../styles/global";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body>
        {children}
        <GlobalStyle />
      </body>
    </html>
  );
}
