import { GlobalStyle } from "../../../styles/global";
import HeaderWebSite from "./components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body>
        <HeaderWebSite />

        {children}
      </body>
      <GlobalStyle />
    </html>
  );
}
